async function fetchData()
{
    const data={
        "data": {
            "name": "ITMR-06-02-2024-FINFORM-Income Tax Savings Maximizer-24-01-05-91700-97335",
            "owner": "springmoneycard@gmail.com",
            "creation": "2024-02-06 13:09:08.369619",
            "modified": "2024-02-06 13:43:57.415833",
            "modified_by": "website.springmoney@gmail.com",
            "docstatus": 0,
            "idx": 0,
            "full_name": "Nikhil Sanjay Narkhedkar",
            "user_email_id": "nikhil.springmoney@gmail.com",
            "phone_number": "9767522788",
            "user_age_in_years": "34",
            "financial_form": "FINFORM-Income Tax Savings Maximizer-24-01-05-91700",
            "is_complete": 1,
            "total_progress": 100.0,
            "income_tax_user": "SPMN-USER-230106-00025",
            "income_tax_lead_profile": "LEADPROF-87774",
            "income_tax_session_token": "SESSTO-FINFORM-Health Check Up Mobile App Sectional Financial Form-23-10-27-33745-Linux Web-097027",
            "income_tax_brand_association": "FINBRAND-Spring Money-30521",
            "income_tax_start_datetime": "2024-02-05 13:03:52",
            "income_tax_complete_datetime": "2024-02-06 13:05:03",
            "income_tax_report_generation_datetime": "2024-02-06 13:05:05",
            "doctype": "Income Tax Maximizer Report",
            "income_tax_comparison_table": [
                
                {
                    "name": "ITRT-EXISTING_OLD_REGIME-06-02-2024-97343",
                    "owner": "website.springmoney@gmail.com",
                    "creation": "2024-02-06 13:09:08.369619",
                    "modified": "2024-02-06 13:43:57.415833",
                    "modified_by": "website.springmoney@gmail.com",
                    "docstatus": 0,
                    "idx": 2,
                    "comparison_type": "EXITING_NEW_REGIME",
                    "annual_income_total": Total_Income,
                    "annual_income_capital_gain": 0.0,
                    "annual_income_rent":Rent_paid,
                    "salary_sub_total": salary,
                    "salary_basic":  Basic_input,
                    "salary_da": DA_input,
                    "salary_hra": HRA_input,
                    "salary_lta": LTA_input,
                    "salary_other_allowance": Other_allowances,
                    "allowance_exemption_total": Total_Exemption_plus_deduction_new_regime,
                    "allowance_exemption_standard_deduction":Standard_deduction_new_regime,
                    "allowance_exemption_hra": 0.0,
                    "allowance_exemption_lta": 0.0,
                    "deduction_under_chapter_vi_a": 0.0,
                    "deduction_under_80c_investments": 0.0,
                    "deduction_under_80ccd_1b_nps": 0.0,
                    "deduction_under_80ccd_2_nps_employer_contribution": 0.0,
                    "deduction_under_80d_insurance_medical_expenditure": 0.0,
                    "deduction_under_80dd_disability": 0.0,
                    "deduction_under_80ddb_special_medical_expenditure": 0.0,
                    "deduction_under_80e_education_loan": 0.0,
                    "deduction_under_80eeb_ev_loan": 0.0,
                    "deduction_under_80gg_rent": 0.0,
                    "deduction_under_donations": 0.0,
                    "interest_on_self_occupied_property": 0.0,
                    "taxable_income_total": Taxable_Income_new_regime,
                    "tax_payable_total":Total_tax_payable_new_regime,
                    "tax_payable_tax_on_above": Tax_On_Above_new_regime,
                    "tax_payable_surcharge": Surcharge_new_regime,
                    "tax_payable_marginal_relief": Marginal_Relief_new_regime,
                    "tax_payable_rebate": Rebate_new_regime,
                    "tax_payable_cess": Cess_new_regime,
                    "parent": "ITMR-06-02-2024-FINFORM-Income Tax Savings Maximizer-24-01-05-91700-97335",
                    "parentfield": "income_tax_comparison_table",
                    "parenttype": "Income Tax Maximizer Report",
                    "doctype": "Income Tax Report Table"
                },
                {
                    "name": "ITRT-EXITING_NEW_REGIME-06-02-2024-97342",
                    "owner": "website.springmoney@gmail.com",
                    "creation": "2024-02-06 13:09:08.369619",
                    "modified": "2024-02-06 13:43:57.415833",
                    "modified_by": "website.springmoney@gmail.com",
                    "docstatus": 0,
                    "idx": 1,
                    "comparison_type": "EXISTING_OLD_REGIME",
                    "annual_income_total": Total_Income,
                    "annual_income_capital_gain": 0.0,
                    "annual_income_rent":Rent_paid,
                    "salary_sub_total": salary,
                    "salary_basic":  Basic_input,
                    "salary_da": DA_input,
                    "salary_hra": HRA_input,
                    "salary_lta": LTA_input,
                    "salary_other_allowance": Other_allowances,
                    "allowance_exemption_total": Total_Exemption_plus_deduction_old_regime,
                    "allowance_exemption_standard_deduction": Standard_deduction,
                    "allowance_exemption_hra": HRA_suggested_old_scheme,
                    "allowance_exemption_lta": 0.0,
                    "deduction_under_chapter_vi_a": 0.0,
                    "deduction_under_80c_investments": 0.0,
                    "deduction_under_80ccd_1b_nps":NPS_50K_old_regime,
                    "deduction_under_80ccd_2_nps_employer_contribution": NPS_Contri_By_Employer_old_regime,
                    "deduction_under_80d_insurance_medical_expenditure": Insurance_Plus_Med_Exp_old_regime,
                    "deduction_under_80dd_disability":Disablity_old_regime ,
                    "deduction_under_80ddb_special_medical_expenditure": Special_medical_expenses_old_regime,
                    "deduction_under_80e_education_loan": Edu_loan_old_regime,
                    "deduction_under_80eeb_ev_loan": Ev_loan,
                    "deduction_under_80gg_rent": Rent_suggested_old_scheme,
                    "deduction_under_donations": 0.0,
                    "interest_on_self_occupied_property": Interest_on_self_occupied_property,
                    "taxable_income_total": Taxable_Income_old_regime,
                    "tax_payable_total": Total_tax_payable_old_regime,
                    "tax_payable_tax_on_above": Tax_On_Above_old_regime,
                    "tax_payable_surcharge":Surcharge_old_regime,
                    "tax_payable_marginal_relief": Marginal_Relief_old_regime,
                    "tax_payable_rebate": Rebate_old_regime,
                    "tax_payable_cess": Cess_old_regime,
                    "parent": "ITMR-06-02-2024-FINFORM-Income Tax Savings Maximizer-24-01-05-91700-97335",
                    "parentfield": "income_tax_comparison_table",
                    "parenttype": "Income Tax Maximizer Report",
                    "doctype": "Income Tax Report Table"
                },
                {
                    "name": "ITRT-RECOMMENDED_OLD_REGIME-06-02-2024-97344",
                    "owner": "website.springmoney@gmail.com",
                    "creation": "2024-02-06 13:09:08.369619",
                    "modified": "2024-02-06 13:43:57.415833",
                    "modified_by": "website.springmoney@gmail.com",
                    "docstatus": 0,
                    "idx": 3,
                    "comparison_type": "RECOMMENDED_OLD_REGIME",
                    "annual_income_total": Total_Income,
                    "annual_income_capital_gain": 0.0,
                    "annual_income_rent":Rent_paid,
                    "salary_sub_total": salary,
                    "salary_basic":  Basic_input,
                    "salary_da": DA_input,
                    "salary_hra": HRA_input,
                    "salary_lta": LTA_input,
                    "salary_other_allowance": Other_allowances,
                    "allowance_exemption_total": 0.0,
                    "allowance_exemption_standard_deduction": 0.0,
                    "allowance_exemption_hra": 0.0,
                    "allowance_exemption_lta": 0.0,
                    "deduction_under_chapter_vi_a": 0.0,
                    "deduction_under_80c_investments": Investment_suggested_old_scheme,
                    "deduction_under_80ccd_1b_nps": NPS_50K_suggested_old_schem,
                    "deduction_under_80ccd_2_nps_employer_contribution": NPS_Contri_By_Employer_suggested_old_scheme,
                    "deduction_under_80d_insurance_medical_expenditure": Insurance_Plus_Med_Exp_suggested_old_scheme,
                    "deduction_under_80dd_disability": Disability_suggested_old_scheme,
                    "deduction_under_80ddb_special_medical_expenditure": Special_medical_expenses_suggested_old_schem,
                    "deduction_under_80e_education_loan":Education_loan_suggested_old_scheme,
                    "deduction_under_80eeb_ev_loan": Ev_loan_suggested_old_scheme,
                    "deduction_under_80gg_rent": Rent_suggested_new_scheme,
                    "deduction_under_donations": 0.0,
                    "interest_on_self_occupied_property": 0.0,
                    "taxable_income_total": Taxable_Income_suggested_old_scheme,
                    "tax_payable_total": Total_tax_payable_suggested_old_scheme,
                    "tax_payable_tax_on_above": Tax_on_above_suggested_old_scheme,
                    "tax_payable_surcharge": Surcharge_suggested_old_scheme,
                    "tax_payable_marginal_relief": Marginal_Relief_suggested_old_scheme,
                    "tax_payable_rebate": Rebate_suggested_old_scheme,
                    "tax_payable_cess": Cess_suggested_old_scheme,
                    "parent": "ITMR-06-02-2024-FINFORM-Income Tax Savings Maximizer-24-01-05-91700-97335",
                    "parentfield": "income_tax_comparison_table",
                    "parenttype": "Income Tax Maximizer Report",
                    "doctype": "Income Tax Report Table"
                },
                {
                    "name": "ITRT-RECOMMENDED_NEW_REGIME-06-02-2024-97345",
                    "owner": "website.springmoney@gmail.com",
                    "creation": "2024-02-06 13:09:08.369619",
                    "modified": "2024-02-06 13:43:57.415833",
                    "modified_by": "website.springmoney@gmail.com",
                    "docstatus": 0,
                    "idx": 4,
                    "comparison_type": "RECOMMENDED_NEW_REGIME",
                    "annual_income_total": Total_Income,
                    "annual_income_capital_gain": 0.0,
                    "annual_income_rent":Rent_paid,
                    "salary_sub_total": salary,
                    "salary_basic":  Basic_input,
                    "salary_da": DA_input,
                    "salary_hra": HRA_input,
                    "salary_lta": LTA_input,
                    "salary_other_allowance": Other_allowances,
                    "allowance_exemption_total": Total_Exemption_plus_deduction_suggested_new_scheme,
                    "allowance_exemption_standard_deduction": 0.0,
                    "allowance_exemption_hra": 0.0,
                    "allowance_exemption_lta": 0.0,
                    "deduction_under_chapter_vi_a": 0.0,
                    "deduction_under_80c_investments": Investment_suggested_new_scheme,
                    "deduction_under_80ccd_1b_nps": NPS_50K_suggested_new_scheme,
                    "deduction_under_80ccd_2_nps_employer_contribution": NPS_Contri_By_Employer__suggested_new_scheme,
                    "deduction_under_80d_insurance_medical_expenditure": Insurance_Plus_Med_Exp_suggested_new_scheme,
                    "deduction_under_80dd_disability": Disability_Answer__suggested_new_scheme,
                    "deduction_under_80ddb_special_medical_expenditure": Special_med_Answer__suggested_new_scheme,
                    "deduction_under_80e_education_loan":Edu_loan__suggested_new_scheme,
                    "deduction_under_80eeb_ev_loan": Ev_loan__suggested_new_scheme,
                    "deduction_under_80gg_rent": Rent_suggested_new_scheme,
                    "deduction_under_donations": 0.0,
                    "interest_on_self_occupied_property": 0.0,
                    "taxable_income_total": Taxable_Income_suggested_new_scheme,
                    "tax_payable_total": Total_tax_payable_suggested_new_scheme,
                    "tax_payable_tax_on_above":  Tax_On_Above_suggested_new_scheme,
                    "tax_payable_surcharge": Surcharge_suggested_new_scheme,
                    "tax_payable_marginal_relief": Marginal_Relief_suggested_new_scheme,
                    "tax_payable_rebate": Rebate_suggested_new_scheme,
                    "tax_payable_cess": Cess_suggested_new_scheme,
                    "parent": "ITMR-06-02-2024-FINFORM-Income Tax Savings Maximizer-24-01-05-91700-97335",
                    "parentfield": "income_tax_comparison_table",
                    "parenttype": "Income Tax Maximizer Report",
                    "doctype": "Income Tax Report Table"
                }
            ]
        }
    }
    let response = await fetch(`${process.env.BASE_URL}/api/resource/Income Tax Maximizer Report/ITMR-06-02-2024-FINFORM-Income Tax Savings Maximizer-24-01-05-91700-97335`, {
        method: "POST", // or 'PUT'
        headers: {
          "Content-Type": "application/json",
          "Authorization":`token ${process.env.AUTH_TOKEN}`,
        },
        body: JSON.stringify(data),
    });
    // console.log(await response.json())
}